use crate::names::*;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RoutedTool {
    ContainerExec,
    ContainerCopy,
    ReadFile,
    ListFiles,
    ApplyPatch,
    SearchFiles,
    SpawnAgent,
    SendInput,
    WaitAgent,
    ListAgents,
    CloseAgent,
    ResumeAgent,
    ListMcpResources,
    ListMcpResourceTemplates,
    ReadMcpResource,
    SaveTaskPlan,
    SubmitReviewResult,
    UpdateTodoList,
    RequestUserInput,
    SaveArtifact,
    GithubApiRequest,
    QueueProjectReviewPrs,
    GitStatus,
    GitDiff,
    GitBranch,
    GitFetch,
    GitCommit,
    GitPush,
    GitWorkspaceInfo,
    GitSyncDefaultBranch,
    Mcp(String),
    Unknown(String),
}

pub fn route_tool(name: &str) -> RoutedTool {
    match name {
        TOOL_CONTAINER_EXEC => RoutedTool::ContainerExec,
        TOOL_CONTAINER_COPY => RoutedTool::ContainerCopy,
        TOOL_READ_FILE => RoutedTool::ReadFile,
        TOOL_LIST_FILES => RoutedTool::ListFiles,
        TOOL_APPLY_PATCH => RoutedTool::ApplyPatch,
        TOOL_SEARCH_FILES => RoutedTool::SearchFiles,
        TOOL_SPAWN_AGENT => RoutedTool::SpawnAgent,
        TOOL_SEND_INPUT => RoutedTool::SendInput,
        TOOL_WAIT_AGENT => RoutedTool::WaitAgent,
        TOOL_LIST_AGENTS => RoutedTool::ListAgents,
        TOOL_CLOSE_AGENT => RoutedTool::CloseAgent,
        TOOL_RESUME_AGENT => RoutedTool::ResumeAgent,
        TOOL_LIST_MCP_RESOURCES => RoutedTool::ListMcpResources,
        TOOL_LIST_MCP_RESOURCE_TEMPLATES => RoutedTool::ListMcpResourceTemplates,
        TOOL_READ_MCP_RESOURCE => RoutedTool::ReadMcpResource,
        TOOL_SAVE_TASK_PLAN => RoutedTool::SaveTaskPlan,
        TOOL_SUBMIT_REVIEW_RESULT => RoutedTool::SubmitReviewResult,
        TOOL_UPDATE_TODO_LIST => RoutedTool::UpdateTodoList,
        TOOL_REQUEST_USER_INPUT => RoutedTool::RequestUserInput,
        TOOL_SAVE_ARTIFACT => RoutedTool::SaveArtifact,
        TOOL_GITHUB_API_REQUEST => RoutedTool::GithubApiRequest,
        TOOL_QUEUE_PROJECT_REVIEW_PRS => RoutedTool::QueueProjectReviewPrs,
        TOOL_GIT_STATUS => RoutedTool::GitStatus,
        TOOL_GIT_DIFF => RoutedTool::GitDiff,
        TOOL_GIT_BRANCH => RoutedTool::GitBranch,
        TOOL_GIT_FETCH => RoutedTool::GitFetch,
        TOOL_GIT_COMMIT => RoutedTool::GitCommit,
        TOOL_GIT_PUSH => RoutedTool::GitPush,
        TOOL_GIT_WORKSPACE_INFO => RoutedTool::GitWorkspaceInfo,
        TOOL_GIT_SYNC_DEFAULT_BRANCH => RoutedTool::GitSyncDefaultBranch,
        tool_name if tool_name.starts_with("mcp__") => RoutedTool::Mcp(tool_name.to_string()),
        tool_name => RoutedTool::Unknown(tool_name.to_string()),
    }
}
