[workspace]
release = false
publish = false
changelog_update = false
git_release_enable = false
git_tag_enable = false

[[package]]
name = "mai-relay"
release = true
publish = false
git_only = true
changelog_update = true
git_release_enable = true
git_release_name = "{{ package }} v{{ version }}"
git_release_latest = true
git_tag_enable = true
git_tag_name = "{{ package }}-v{{ version }}"
