use std::sync::Arc;

use axum::Router;
use axum::routing::{get, post};
use tower_http::cors::CorsLayer;
use tower_http::trace::TraceLayer;

use crate::handlers;
use crate::handlers::state::AppState;
use crate::http::routes;

pub(crate) fn create_router(state: Arc<AppState>) -> Router {
    Router::new()
        .route("/", get(routes::assets::index))
        .route("/health", get(routes::health::health))
        .route(
            "/providers",
            get(handlers::providers::get_providers).put(handlers::providers::save_providers),
        )
        .route(
            "/providers/{id}/test",
            post(handlers::providers::test_provider),
        )
        .route(
            "/mcp-servers",
            get(handlers::providers::get_mcp_servers).put(handlers::providers::save_mcp_servers),
        )
        .route(
            "/git/accounts",
            get(handlers::git_accounts::list_git_accounts)
                .post(handlers::git_accounts::save_git_account),
        )
        .route(
            "/git/accounts/default",
            axum::routing::put(handlers::git_accounts::set_default_git_account),
        )
        .route(
            "/git/accounts/{id}",
            axum::routing::put(handlers::git_accounts::save_git_account_by_id)
                .delete(handlers::git_accounts::delete_git_account),
        )
        .route(
            "/git/accounts/{id}/verify",
            post(handlers::git_accounts::verify_git_account),
        )
        .route(
            "/git/accounts/{id}/repositories",
            get(handlers::git_accounts::list_git_account_repositories),
        )
        .route(
            "/git/accounts/{id}/repositories/{owner}/{repo}/packages",
            get(handlers::git_accounts::list_git_account_repository_packages),
        )
        .route(
            "/runtime/defaults",
            get(handlers::config::get_runtime_defaults),
        )
        .route(
            "/settings/github",
            get(handlers::github_app::get_github_settings)
                .put(handlers::github_app::save_github_settings),
        )
        .route(
            "/settings/github-app",
            get(handlers::github_app::get_github_app_settings)
                .put(handlers::github_app::save_github_app_settings),
        )
        .route(
            "/settings/relay",
            get(handlers::github_app::get_relay_settings)
                .put(handlers::github_app::save_relay_settings),
        )
        .route(
            "/github/app-manifest/start",
            post(handlers::github_app::start_github_app_manifest),
        )
        .route(
            "/github/app-manifest/callback",
            get(handlers::github_app::complete_github_app_manifest),
        )
        .route(
            "/github/app-installation/callback",
            get(handlers::github_app::github_app_installation_callback),
        )
        .route(
            "/github/app-installation/start",
            post(handlers::github_app::start_github_app_installation),
        )
        .route("/relay/status", get(handlers::github_app::get_relay_status))
        .route("/relay/update", get(handlers::github_app::get_relay_update))
        .route(
            "/relay/update:check",
            post(handlers::github_app::check_relay_update),
        )
        .route(
            "/relay/update:apply",
            post(handlers::github_app::apply_relay_update),
        )
        .route(
            "/relay/update:rollback",
            post(handlers::github_app::rollback_relay_update),
        )
        .route(
            "/github/installations",
            get(handlers::github_app::list_github_installations),
        )
        .route(
            "/github/installations:refresh",
            post(handlers::github_app::refresh_github_installations),
        )
        .route(
            "/github/installations/{id}/repositories",
            get(handlers::github_app::list_github_repositories),
        )
        .route(
            "/github/installations/{id}/repositories/{owner}/{repo}/packages",
            get(handlers::github_app::list_github_repository_packages),
        )
        .route(
            "/provider-presets",
            get(handlers::config::get_provider_presets),
        )
        .route("/skills", get(handlers::config::list_skills))
        .route(
            "/skills/config",
            axum::routing::put(handlers::config::save_skills_config),
        )
        .route(
            "/agent-profiles",
            get(handlers::config::list_agent_profiles),
        )
        .route(
            "/agent-profiles:reload",
            post(handlers::config::list_agent_profiles),
        )
        .route(
            "/agent-config",
            get(handlers::config::get_agent_config).put(handlers::config::save_agent_config),
        )
        .route("/events", get(handlers::events::events))
        .route(
            "/environments",
            get(handlers::environments::list_environments)
                .post(handlers::environments::create_environment),
        )
        .route(
            "/environments:ensure-default",
            post(handlers::environments::ensure_default_environment),
        )
        .route(
            "/environments/{id}",
            get(handlers::environments::get_environment),
        )
        .route(
            "/environments/{id}/conversations",
            post(handlers::environments::create_conversation),
        )
        .route(
            "/environments/{id}/conversations/{session_id}/messages",
            post(handlers::environments::send_conversation_message),
        )
        .route(
            "/projects",
            get(handlers::projects::list_projects).post(handlers::projects::create_project),
        )
        .route(
            "/projects/{id}",
            get(handlers::projects::get_project)
                .patch(handlers::projects::update_project)
                .delete(handlers::projects::delete_project),
        )
        .route(
            "/projects/{id}/messages",
            post(handlers::projects::send_project_message),
        )
        .route(
            "/projects/{id}/review-runs",
            get(handlers::projects::list_project_review_runs),
        )
        .route(
            "/projects/{id}/review-runs/{run_id}",
            get(handlers::projects::get_project_review_run),
        )
        .route(
            "/projects/{id}/skills",
            get(handlers::projects::list_project_skills),
        )
        .route(
            "/projects/{id}/skills/detect",
            post(handlers::projects::detect_project_skills),
        )
        .route(
            "/projects/{id}/cancel",
            post(handlers::projects::cancel_project),
        )
        .route(
            "/agents",
            get(handlers::agents::list_agents).post(handlers::agents::create_agent),
        )
        .route(
            "/agents/{id}",
            get(handlers::agents::get_agent)
                .delete(handlers::agents::delete_agent)
                .patch(handlers::agents::update_agent)
                .post(handlers::agents::cancel_agent_colon),
        )
        .route(
            "/agents/{id}/messages",
            post(handlers::agents::send_message),
        )
        .route(
            "/agents/{id}/sessions",
            post(handlers::agents::create_session),
        )
        .route(
            "/agents/{id}/sessions/{session_id}/messages",
            post(handlers::agents::send_session_message),
        )
        .route(
            "/agents/{id}/sessions/{session_id}/tool-calls/{call_id}",
            get(handlers::agents::get_session_tool_trace),
        )
        .route("/agents/{id}/logs", get(handlers::agents::list_agent_logs))
        .route(
            "/agents/{id}/tool-calls",
            get(handlers::agents::list_tool_traces),
        )
        .route(
            "/agents/{id}/tool-calls/{call_id}",
            get(handlers::agents::get_tool_trace),
        )
        .route(
            "/agents/{id}/turns/{turn_id}/cancel",
            post(handlers::agents::cancel_agent_turn),
        )
        .route(
            "/agents/{id}/files:upload",
            post(handlers::agents::upload_file),
        )
        .route(
            "/agents/{id}/files:download",
            get(handlers::agents::download_file),
        )
        .route(
            "/environments/{id}/artifacts",
            get(handlers::environments::list_artifacts),
        )
        .route(
            "/artifacts/{id}/download",
            get(handlers::environments::download_artifact),
        )
        .route("/agents/{id}/cancel", post(handlers::agents::cancel_agent))
        .fallback(get(routes::assets::static_fallback))
        .layer(CorsLayer::permissive())
        .layer(TraceLayer::new_for_http())
        .with_state(state)
}
